### ISSUE TITLE
Dropdown Function

### ISSUE THREAD

**Issue by justinlosh** [pitaj/nodebb-plugin-header-extend#2] opened 2015-01-21 01:03 UTC
Hello,
Dropdown menus don't seem to be functioning, unless you make the first link a valid link. For example I would like to organize the menu:

Connect (#)

> Facebook (http://www.facebook.com)
> Twitter (http://www.twitter.com)
> YouTube (http://www.youtube.com)

**Comment by pitaj** [comment] 2015-01-21 03:20
Can you provide a gif or video of this happening? Are there any errors in the JS console?

The link for the dropdown doesn't matter anyways, it is automatically changed to "#" when it is made a menu header. 

I am aware that sometimes the dropdown messes up when it is first made. Refreshing the page seems to fix it. 

I have had to hack around the tooltip behavior by using a timeout delay before my code is executed in order for it to execute after the timeout.

**Comment by justinlosh** [comment] 2015-01-21 04:45
Hello,
There are no errors in the JS Console. I've tried restarting and reloading NodeBB, as well as refreshing the page.

![GIF Screen Cap](http://i.imgur.com/JEJmRFX.gif)

GIF: http://i.imgur.com/JEJmRFX.gif

**Comment by pitaj** [comment] 2015-01-21 04:57
Are there any errors in the NodeBB console or log?

Try running it in dev mode: `./nodebb dev`

**Comment by justinlosh** [comment] 2015-01-21 05:00
Sorry, not any issues from the ACP > Logs. I am running on the NodeBB SaaS, so I don't have access. Sorry, I know I'm not giving you much to go on. Wasn't sure if you could replicate it on your end also.

**Comment by pitaj** [comment] 2015-01-21 05:11
![kinda works](http://i.imgur.com/bbdbZ4U.png)

It's working for me (except for that goddamn space, which I swear I'm gonna fix)

**Comment by justinlosh** [comment] 2015-01-21 05:15
I can get it to work (with the space) in Internet Explorer and Firefox, but not Chrome.

**Comment by pitaj** [comment] 2015-01-21 05:21
That is super weird. I have no idea what is causing that problem. I'm on Chrome.

What version of Chrome are you on?  Do you have any user scripts? It is a problem with CSS probably, but I don't know what the problem could be.

**Comment by justinlosh** [comment] 2015-01-21 05:24
I'm using  39.0.2171.99 m (Windows 8 x64). No, no user scripts. I find this issue very odd, I mean normally you see an error or something.

**Comment by pitaj** [comment] 2015-01-21 05:25
Same version of Chrome. You don't have any custom css on your site do you?

**Comment by justinlosh** [comment] 2015-01-21 05:28
I only have the following, to hide the links from the Custom Pages Plugin. But I deleted all of it, prior to filing the issue. Still having the same issue.

```
li.tos-link {
    display:none;
}
li.privacy-link {
    display:none;
}
li.gs-link {
    display:none;
}
li.contact-link {
    display:none;
}
```

**Comment by pitaj** [comment] 2015-01-21 05:54
I have no idea what could be causing this. 

You could try clearing your cache.

If that doesn't work, restart your computer. 
If that doesn't work, try reinstalling Chrome. I imagine it is something to do with your install of Chrome itself. 

BTW, I fixed it so it no longer requires that nasty hack, and I'm going to release v0.0.3 in the coming minutes.

**Comment by pitaj** [comment] 2015-01-21 06:46
v0.0.3 is released, try updating when it gets recognized by nbbpm and see if the changes fit it.

**Comment by justinlosh** [comment] 2015-01-21 08:00
That last update seems to have fixed it. The only issue is when you hover over an item in the menu, I get the following:

![Screen Cap](http://i.imgur.com/zDvgrQq.png)

**Comment by pitaj** [comment] 2015-01-21 08:23
That is caused by your theme overriding the `background-color` style of the links. You can put this in the custom css to fix it:

``` css
.navbar-default .navbar-nav>li>a.header-extend-menu-item:hover, 
.navbar-default .navbar-nav>li>a.header-extend-menu-item:focus {
   background-color: white;
}
```

Also, I don't think you're on v0.0.3, you may be on v0.0.2
v0.0.3 allows for menus to become wider so there is no weird wrapping.

**Comment by justinlosh** [comment] 2015-01-21 08:25
Awesome, thanks! It says I'm on 0.0.3.

**Comment by pitaj** [comment] 2015-01-21 08:42
Okay, I fixed that bug. Newest version is now 0.0.4

I'm closing this issue as it appears to be resolved.

Closed by c6ee86474d29d1d5aec3aa37cf36f0e0ec8de0be

**Closed as completed** 2015-01-21 08:42 UTC

**Comment by justinlosh** [comment] 2015-01-21 08:44
I greatly appreciate your help and how responsive you are!

**Comment by pitaj** [comment] 2015-01-21 08:45
I try.

Time for sleep
